/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Canton;
import clases.Provincia;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import logica.LogConsulta;

/**
 *
 * @author Avδρέας
 */
public class Provincias_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Provincias_GUI
     */
    ArrayList<Provincia> ObjPro = new ArrayList();
    ArrayList<Canton> ObjCanton = new ArrayList();

    public Provincias_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        CargarProvincias();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxPro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 550, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PROVINCIAS DEL ECUADOR ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 110));

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 170, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Provincias");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantones");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jComboBoxCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCanActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxCan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 550, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProActionPerformed
        // TODO add your handling code here:
        CargarCantones((Provincia) this.jComboBoxPro.getSelectedItem());
    }//GEN-LAST:event_jComboBoxProActionPerformed

    private void jComboBoxCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provincias_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provincias_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provincias_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provincias_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provincias_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxCan;
    private javax.swing.JComboBox<String> jComboBoxPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public void CargarProvincias() {
        LogConsulta objLC = new LogConsulta();
        ArrayList<Provincia> listaPro = new ArrayList<Provincia>();
        try {
            listaPro = objLC.ObtenerProvincia();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
            System.err.println(e);
        }
        DefaultComboBoxModel dlmN = new DefaultComboBoxModel();
        Provincia objPro = new Provincia(-1, "Selecione..");
        dlmN.addElement(objPro);
        for (Provincia p : listaPro) {
            dlmN.addElement(p);
        }
        this.jComboBoxPro.setModel(dlmN);

    }

    public void CargarCantones(Provincia ProvinciaSelect) {
        ArrayList<Canton> listaCan = new ArrayList<Canton>();
        Canton objCan = new Canton(-1, "seleciones....", ProvinciaSelect);
        LogConsulta objLC = new LogConsulta();

        try {
            listaCan = objLC.ObtenerCanton(ProvinciaSelect);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
            System.err.println(e);
        }
        DefaultComboBoxModel dlm = new DefaultComboBoxModel();

        dlm.addElement(objCan);
        for (Canton c : listaCan) {
            dlm.addElement(c);
        }
        this.jComboBoxCan.setModel(dlm);

    }
}
