
package GUI;

/**
 *
 * @author STALIN
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.setExtendedState(frmInicio.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reserva de Habitacion y Gestion de Ventas - HOTEL CATAMAYO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        lblIdUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNombreRol = new javax.swing.JLabel();
        lblNombreFuncionalidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 204, 204));

        lblIdUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIdUsuario.setText("jLabel1");
        escritorio.add(lblIdUsuario);
        lblIdUsuario.setBounds(200, 40, 110, 14);

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreUsuario.setText("jLabel2");
        escritorio.add(lblNombreUsuario);
        lblNombreUsuario.setBounds(200, 70, 110, 14);

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLogin.setText("jLabel3");
        escritorio.add(lblLogin);
        lblLogin.setBounds(200, 100, 110, 14);

        lblNombreRol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreRol.setText("jLabel4");
        escritorio.add(lblNombreRol);
        lblNombreRol.setBounds(200, 130, 110, 14);

        lblNombreFuncionalidad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombreFuncionalidad.setText("jLabel5");
        escritorio.add(lblNombreFuncionalidad);
        lblNombreFuncionalidad.setBounds(210, 170, 260, 100);

        jLabel1.setText("ID Usuario:");
        escritorio.add(jLabel1);
        jLabel1.setBounds(40, 40, 120, 14);

        jLabel2.setText("Nombre Usuario:");
        escritorio.add(jLabel2);
        jLabel2.setBounds(40, 70, 120, 14);

        jLabel3.setText("Login:");
        escritorio.add(jLabel3);
        jLabel3.setBounds(40, 100, 100, 14);

        jLabel4.setText("Nombre Rol:");
        escritorio.add(jLabel4);
        jLabel4.setBounds(40, 140, 120, 14);

        jLabel5.setText("Nombre Funcionalidad:");
        escritorio.add(jLabel5);
        jLabel5.setBounds(40, 210, 130, 14);

        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        menuBar.add(mnuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblLogin;
    public static javax.swing.JLabel lblNombreFuncionalidad;
    public static javax.swing.JLabel lblNombreRol;
    public static javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables

}
