package GUI;

import BL.fFuncionalidad;
import BL.fRol;
import BL.fRol_Funcionalidad;
import BL.fRol_Usuario;
import BL.fUsuario;
import DAT.DFuncionalidad_Rol;
import DAT.DRol;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author STALIN
 */
public class GUIRol_Funcionalidad extends javax.swing.JFrame {

    /**
     * Creates new form GUIRolUsuario
     */
    public GUIRol_Funcionalidad() {
        initComponents();

        mostrar("");
        inhabilitar();
        mostrarROL_Funcionalidad("");
    }

    private String accion = "guardar";

    void ocultar_columnas() {
        jTableFuncionalidad.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableFuncionalidad.getColumnModel().getColumn(0).setMinWidth(0);
        jTableFuncionalidad.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTableRol.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableRol.getColumnModel().getColumn(0).setMinWidth(0);
        jTableRol.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTableRol_Funcionalidad.getColumnModel().getColumn(2).setMaxWidth(0);
        jTableRol_Funcionalidad.getColumnModel().getColumn(2).setMinWidth(0);
        jTableRol_Funcionalidad.getColumnModel().getColumn(2).setPreferredWidth(0);

    }

    void inhabilitar() {
        txtIdRol.setVisible(false);

        txtDescripcion.setEnabled(false);
        cboRolNombre.setEnabled(false);

        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);

        //Usuario        
        txtId_fun.setVisible(false);

        txtFun_descripcion.setEnabled(false);
        cboFun_Nombre.setEnabled(false);

        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);

    }

    //habilitar Usuarios y roles
    void habilitar() {
        txtId_fun.setVisible(false);

        txtFun_descripcion.setEnabled(true);
        cboFun_Nombre.setEnabled(true);

        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(true);

        //Roles
        txtIdRol.setVisible(false);

        txtDescripcion.setEnabled(true);
        cboRolNombre.setEnabled(true);

    }

    //Mostrar Usuarios y roles
    void mostrar(String buscar) {
        try {
            DefaultTableModel modeloR;
            DefaultTableModel modeloF;

            fRol funcR = new fRol();
            fFuncionalidad funcF = new fFuncionalidad();

            modeloR = funcR.mostrar(buscar);
            modeloF = funcF.mostrar(buscar);

            jTableRol.setModel(modeloR);
            jTableFuncionalidad.setModel(modeloF);

            //ocultar_columnas();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    void mostrarROL_Funcionalidad(String buscar) {
        try {

            DefaultTableModel modeloRF;

            fRol_Funcionalidad funRF = new fRol_Funcionalidad();

            modeloRF = funRF.mostrarRF(buscar);

            jTableRol_Funcionalidad.setModel(modeloRF);
            //ocultar_columnas();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    void mostrarAdministrador(String buscar) {
        try {
            DefaultTableModel modelo;
            fRol_Funcionalidad func = new fRol_Funcionalidad();
            modelo = func.mostrarRUAdministrador(buscar);

            jTableFuncionalidad.setModel(modelo);
            //ocultar_columnas();

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionalidad = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRol = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRol_Funcionalidad = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtId_fun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFun_descripcion = new javax.swing.JTextField();
        txtIdRol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        cboRolNombre = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        cboFun_Nombre = new javax.swing.JComboBox<>();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableFuncionalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFuncionalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionalidadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableFuncionalidadMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionalidad);

        jLabel1.setText("Funcionalidad");

        jTableRol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRolMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableRol);

        jLabel2.setText("Rol");

        jLabel3.setText("Usuario-Rol");

        jTableRol_Funcionalidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRol_Funcionalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRol_FuncionalidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableRol_FuncionalidadMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTableRol_Funcionalidad);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Buscar por Id Funcionalidad");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel4.setText("Funcionalidad Nombre:");

        jLabel5.setText("Funcionalidad Descripcion");

        jLabel8.setText("Rol Nombre:");

        jLabel9.setText("Rol Descripcion:");

        cboRolNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "SECRETARIA", "CLIENTE", " " }));

        cboFun_Nombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso de Pacientes", "Ingreso de Doctores", "Eliminacion de Pacientes", "Eliminacion de Doctores", "Actualizacion de Pacientes", "Actualizacion de Doctores", "Reporte de Citas", "Resporte de Doctores", "Reporte de Pacientes" }));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFun_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboFun_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(46, 46, 46)
                                    .addComponent(cboRolNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId_fun, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdRol, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(259, 259, 259)
                            .addComponent(btnEliminar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(274, 274, 274)
                            .addComponent(btnConsultar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)))
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtId_fun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(cboFun_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtFun_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(cboRolNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtIdRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGap(24, 24, 24)
                .addComponent(btnEliminar)
                .addGap(173, 173, 173))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (!txtIdRol.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de Eliminar el Rol- Funcionalidad?", "Confirmar", 2);

            if (confirmacion == 0) {

                DFuncionalidad_Rol dtsRF = new DFuncionalidad_Rol();
                fRol_Funcionalidad funRF = new fRol_Funcionalidad();

                dtsRF.setIntRol_id(Integer.parseInt(txtIdRol.getText()));
                funRF.eliminar(dtsRF);
                mostrarROL_Funcionalidad("");
                inhabilitar();

            }

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTableFuncionalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionalidadMouseClicked
        // TODO add your handling code here:

        habilitar();
        btnGuardar.setText("Guardar");
        accion = "guardar";

        int fila = jTableFuncionalidad.rowAtPoint(evt.getPoint());

        txtId_fun.setText(jTableFuncionalidad.getValueAt(fila, 0).toString());
        txtFun_descripcion.setText(jTableFuncionalidad.getValueAt(fila, 1).toString());

        cboFun_Nombre.setSelectedItem(jTableFuncionalidad.getValueAt(fila, 2).toString());

    }//GEN-LAST:event_jTableFuncionalidadMouseClicked

    private void jTableRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRolMouseClicked
        // TODO add your handling code here:
        habilitar();
        btnGuardar.setText("Guardar");
        accion = "guardar";

        int valor = 4;
        // .setText(Integer.toString(valor))

        if (txtIdRol.getText() == Integer.toString(valor)) {

            mostrarAdministrador("E");

        }

        int fila = jTableRol.rowAtPoint(evt.getPoint());

        txtIdRol.setText(jTableRol.getValueAt(fila, 0).toString());
        txtDescripcion.setText(jTableRol.getValueAt(fila, 2).toString());

        cboRolNombre.setSelectedItem(jTableRol.getValueAt(fila, 1).toString());
    }//GEN-LAST:event_jTableRolMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        DFuncionalidad_Rol dtsRF = new DFuncionalidad_Rol();
        fRol_Funcionalidad funRF = new fRol_Funcionalidad();

        dtsRF.setIntFun_id(Integer.parseInt(txtId_fun.getText()));
        dtsRF.setIntRol_id(Integer.parseInt(txtIdRol.getText()));

        if (accion.equals("guardar")) {
            if (funRF.insertar(dtsRF)) {
                JOptionPane.showMessageDialog(rootPane, "El rol Funcionalidad fue registrado satisfactoriamente");
                mostrarROL_Funcionalidad("");
                inhabilitar();
            }
        } else if (accion.equals("editar")) {
            dtsRF.setIntRol_id(Integer.parseInt(txtIdRol.getText()));
            dtsRF.setIntFun_id(Integer.parseInt(txtId_fun.getText()));
            if (funRF.editar(dtsRF)) {
                JOptionPane.showMessageDialog(rootPane, "El rol Funcionalidad fue Editado satisfactoriamente");
                mostrarROL_Funcionalidad("");
                inhabilitar();
            }
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTableRol_FuncionalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRol_FuncionalidadMouseClicked
        // TODO add your handling code here:
        btnEditar.setText("Editar");
        habilitar();
        btnEliminar.setEnabled(true);
        accion = "editar";

        int fila = jTableRol_Funcionalidad.rowAtPoint(evt.getPoint());
        txtIdRol.setText(jTableRol_Funcionalidad.getValueAt(fila, 0).toString());
        cboRolNombre.setSelectedItem(jTableRol_Funcionalidad.getValueAt(fila, 1).toString());
        txtDescripcion.setText(jTableRol_Funcionalidad.getValueAt(fila, 2).toString());
        txtId_fun.setText(jTableRol_Funcionalidad.getValueAt(fila, 3).toString());
        cboFun_Nombre.setSelectedItem(jTableRol_Funcionalidad.getValueAt(fila, 4).toString());
        txtFun_descripcion.setText(jTableRol_Funcionalidad.getValueAt(fila, 5).toString());


    }//GEN-LAST:event_jTableRol_FuncionalidadMouseClicked

    private void jTableFuncionalidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionalidadMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTableFuncionalidadMousePressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnGuardar.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        mostrarROL_Funcionalidad(txtBuscar.getText());

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        DFuncionalidad_Rol dtsRF = new DFuncionalidad_Rol();
        fRol_Funcionalidad funRF = new fRol_Funcionalidad();

        dtsRF.setIntFun_id(Integer.parseInt(txtId_fun.getText()));
        dtsRF.setIntRol_id(Integer.parseInt(txtIdRol.getText()));

        if (accion.equals("editar")) {
            if (funRF.editar(dtsRF)) {
                JOptionPane.showMessageDialog(rootPane, "El rol Funcionalidad fue Editado satisfactoriamente");
                mostrarROL_Funcionalidad("");
                inhabilitar();
            }
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void jTableRol_FuncionalidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRol_FuncionalidadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableRol_FuncionalidadMouseEntered

    /**
     * * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRol_Funcionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRol_Funcionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRol_Funcionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRol_Funcionalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRol_Funcionalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboFun_Nombre;
    private javax.swing.JComboBox<String> cboRolNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFuncionalidad;
    private javax.swing.JTable jTableRol;
    private javax.swing.JTable jTableRol_Funcionalidad;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFun_descripcion;
    private javax.swing.JTextField txtIdRol;
    private javax.swing.JTextField txtId_fun;
    // End of variables declaration//GEN-END:variables
}
