/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.AnioLectivo;
import Clases.Estudiante;
import Clases.Grado;
import Clases.Matricula;
import Clases.Representante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.logicaAnio;
import logica.logicaGrado;
import logica.logicaMatricula;
import logica.logicaRepresentante;

/**
 *
 * @author STALIN
 */
public class CrearMatricula extends javax.swing.JFrame {

    /**
     * Creates new form CrearMatricula
     */
    logicaRepresentante objLoRepresentante = new logicaRepresentante();
    logicaMatricula objLoMatricula = new logicaMatricula();
    logicaAnio objLoAnio = new logicaAnio();
    logicaGrado objloGrado = new logicaGrado();
    Matricula objMatricula = new Matricula();
    Estudiante objEstudiante = new Estudiante();
    Representante objRepresentante = new Representante();
    Grado objGrado = new Grado();
    public CrearMatricula() {
        initComponents();
        ListarRepresentantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRepresentante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstudiante = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAnio = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaGrado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        observacion = new javax.swing.JTextField();
        matricular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaRepresentante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaRepresentante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRepresentanteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRepresentante);

        jLabel1.setText("Representante");

        jLabel2.setText("Estudiante");

        tablaEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEstudianteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEstudiante);

        jLabel3.setText("Anio");

        tablaAnio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAnioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaAnio);

        tablaGrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaGrado);

        jLabel4.setText("grado");

        jLabel5.setText("Correo:");

        jLabel6.setText("Celular:");

        celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celularKeyTyped(evt);
            }
        });

        jLabel7.setText("Observacion:");

        matricular.setText("Matricular");
        matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(276, 276, 276))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132)
                                .addComponent(matricular))
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(observacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(matricular)))
                .addGap(52, 95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaRepresentanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRepresentanteMouseClicked
        // TODO add your handling code here:
        int row = this.tablaRepresentante.getSelectedRow();
        String cedulaRep = this.tablaRepresentante.getValueAt(row, 2).toString();
        int cedula = Integer.parseInt(cedulaRep);
        Representante objRepresentante = new Representante();
        objRepresentante.setCedula(cedula);
        objRepresentante.getCedula();
        
        ListarEstudiantes(objRepresentante);
        
    }//GEN-LAST:event_tablaRepresentanteMouseClicked

    private void tablaEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudianteMouseClicked
        // TODO add your handling code here:
        ListarAnio();
        
    }//GEN-LAST:event_tablaEstudianteMouseClicked

    private void tablaAnioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAnioMouseClicked
        // TODO add your handling code here:
        int row = this.tablaAnio.getSelectedRow();
        String idA = this.tablaAnio.getValueAt(row, 0).toString();
        int id = Integer.parseInt(idA);
        AnioLectivo objAnioLectivo = new AnioLectivo();
        objAnioLectivo.setIdAnioLectivo(id);
        objAnioLectivo.getIdAnioLectivo();
        ListarGrado(objAnioLectivo);
    }//GEN-LAST:event_tablaAnioMouseClicked

    private void matricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricularActionPerformed
        // TODO add your handling code here:
        int rowG = this.tablaGrado.getSelectedRow();
        String G = this.tablaAnio.getValueAt(rowG, 0).toString();
        int gra = Integer.parseInt(G);
        objGrado.setIdGrado(gra);
        objGrado.getIdGrado();
        int rowE = this.tablaEstudiante.getSelectedRow();
        String E = this.tablaEstudiante.getValueAt(rowG, 0).toString();
        int est = Integer.parseInt(E);
        objEstudiante.setIdEstudiante(est);
        objEstudiante.getIdEstudiante();
        int rowR = this.tablaRepresentante.getSelectedRow();
        String Re = this.tablaRepresentante.getValueAt(rowG, 0).toString();
        int r = Integer.parseInt(Re);
        objRepresentante.setIdRepresentante(r);
        objRepresentante.getIdRepresentante();
        objMatricula.setEstudiante(objEstudiante);
        objMatricula.setGrado(objGrado);
        objMatricula.setRepresentante(objRepresentante);
        objMatricula.setCelular(this.celular.getText());
        objMatricula.setMail(this.correo.getText());
        objMatricula.setObservacion(this.observacion.getText());
        objMatricula.setEstudiante(objEstudiante);
        objMatricula.setGrado(objGrado);
        objMatricula.setRepresentante(objRepresentante);
        if (objLoMatricula.InsertarMatricula(objMatricula)) {
            JOptionPane.showMessageDialog(rootPane, "Matricula creada Correctamente");
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "Error al Crear");
        }
        
    }//GEN-LAST:event_matricularActionPerformed

    private void celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo números.");
        }
    }//GEN-LAST:event_celularKeyTyped

    /**
     * @param args the command line arguments
     */
    
    public void ListarAnio(){
        ArrayList<AnioLectivo> arrayListAnioLectivos = new ArrayList<AnioLectivo>();
        arrayListAnioLectivos = objLoAnio.ListarAnio();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("idAnioLectivo");
        modelo.addColumn("FechaInicio");
        modelo.addColumn("FechaFin");
        modelo.addColumn("Descripcion");
        for (AnioLectivo objAnioLectivo : arrayListAnioLectivos) {
            Object[] fila = new Object[4];
            fila[0] = objAnioLectivo.getIdAnioLectivo();
            fila[1] = objAnioLectivo.getFechaInicio();
            fila[2] = objAnioLectivo.getFechaFin();
            fila[3] = objAnioLectivo.getDescripcion();
            modelo.addRow(fila);
        }
        this.tablaAnio.setModel(modelo);
    }
    public void ListarRepresentantes(){
        ArrayList<Representante> arrayRepresentantes = new ArrayList<Representante>();
        arrayRepresentantes = objLoRepresentante.ListarRepresentante();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("idRepresentante");
        modelo.addColumn("Nombre");
        modelo.addColumn("Cedula");
        modelo.addColumn("Apellidos");
        for (Representante objRepresentante : arrayRepresentantes) {
            Object[] fila = new Object[4];
            fila[0] = objRepresentante.getIdRepresentante();
            fila[1] = objRepresentante.getNombres();
            fila[2] = objRepresentante.getCedula();
            fila[3] = objRepresentante.getApellidos();
            modelo.addRow(fila);
        }
        this.tablaRepresentante.setModel(modelo);
        
        
    }
    public void ListarGrado(AnioLectivo objAnioLectivo){
        ArrayList<Grado> arrayListGrados = new ArrayList<Grado>();
        arrayListGrados = objloGrado.ListarGrados(objAnioLectivo);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("idGrado");
        modelo.addColumn("Codigo ");
        modelo.addColumn("Paralelo");
        modelo.addColumn("Descripcion");
        for (Grado objGrado : arrayListGrados) {
            Object[] fila = new Object[4];
            fila[0] = objGrado.getIdGrado();
            fila[1] = objGrado.getCodigo();
            fila[2] = objGrado.getParalelo();
            fila[3] = objGrado.getDescripcion();
            modelo.addRow(fila);
        }
        this.tablaGrado.setModel(modelo);
        
    }
    public void ListarEstudiantes(Representante objRepresentante){
        ArrayList<Estudiante> arrayListEstudiantes = new ArrayList<Estudiante>();
        arrayListEstudiantes = objLoRepresentante.ListarEstudiantes(objRepresentante);
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("idEstudiante");
        modelo.addColumn("nombre ");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Edad");
        for (Estudiante objEstudiante : arrayListEstudiantes) {
            Object[] fila = new Object[4];
            fila[0] = objEstudiante.getIdEstudiante();
            fila[1] = objEstudiante.getNombres();
            fila[2] = objEstudiante.getApellidos();
            fila[3] = objEstudiante.getEdad();
            modelo.addRow(fila);
        }
        this.tablaEstudiante.setModel(modelo);
   
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celular;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton matricular;
    private javax.swing.JTextField observacion;
    private javax.swing.JTable tablaAnio;
    private javax.swing.JTable tablaEstudiante;
    private javax.swing.JTable tablaGrado;
    private javax.swing.JTable tablaRepresentante;
    // End of variables declaration//GEN-END:variables
}
