/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Depositante;
import Clases.PersonaCuenta;
import Logica.ImpDepositante;
import Logica.ImpPersonaCuenta;
import Logica.ManDepositante;
import Logica.ManPersonaCuenta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Salas
 */
public class Deposito extends javax.swing.JFrame {

    /**
     * Creates new form Deposito
     */
    ImpPersonaCuenta objImpPersonaCuenta = new ImpPersonaCuenta();
    ImpDepositante objImpDepositante = new ImpDepositante();

    ManPersonaCuenta objManPersonaCuenta = new ManPersonaCuenta();
    ManDepositante objManDepositante = new ManDepositante();

    PersonaCuenta objPersonaCuenta = new PersonaCuenta();
    Depositante objDepositante = new Depositante();

    ArrayList<PersonaCuenta> ArrayPersonaCuentas = new ArrayList<PersonaCuenta>();
    ArrayList<Depositante> ArrayDepositante = new ArrayList<Depositante>();

    public Deposito() {
        initComponents();
        this.jTextNombreDeespotiante.setEnabled(false);
        this.jTextApellidoDepositante.setEnabled(false);
        this.jTextCedulaDespositante.setEnabled(false);
        this.jTextDinero.setEnabled(false);
        this.jButtonDespositar.setEnabled(false);

        ArrayPersonaCuentas = objImpPersonaCuenta.ImportarPersonaCuentas();
        ArrayDepositante = objImpDepositante.ImportarDepositante();
        //ArrayClientes = objImpDepositante.GuardaArchivoDepositante(ArrayDepositante);

        //ArrayClientes = objImpDepositante.ImportarDepositante();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNCuenta = new javax.swing.JTextField();
        jButonBuscar = new javax.swing.JButton();
        jTextNombreDeespotiante = new javax.swing.JTextField();
        jTextApellidoDepositante = new javax.swing.JTextField();
        jTextCedulaDespositante = new javax.swing.JTextField();
        jButtonDespositar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextDinero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Depositante: ");

        jLabel2.setText("Apellido del Depositante:");

        jLabel3.setText("Cedula del Depositante:");

        jLabel4.setText("Numero de Cuenta: ");

        jButonBuscar.setText("Buscar");
        jButonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonBuscarActionPerformed(evt);
            }
        });

        jButtonDespositar.setText("Depositar");
        jButtonDespositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDespositarActionPerformed(evt);
            }
        });

        jLabel5.setText("Dinero");

        jTextDinero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDineroKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("DEPOSITAR");

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel3)))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextNCuenta)
                                    .addComponent(jTextNombreDeespotiante)
                                    .addComponent(jTextApellidoDepositante)
                                    .addComponent(jTextCedulaDespositante)
                                    .addComponent(jTextDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(jButonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jButtonDespositar)
                                .addGap(37, 37, 37)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNombreDeespotiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextApellidoDepositante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextCedulaDespositante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDespositar)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonBuscarActionPerformed
        // TODO add your handling code here:
        String nC = "";
        nC = objManPersonaCuenta.BuscarPersonaCuenta(ArrayPersonaCuentas, this.jTextNCuenta.getText());

        if (nC.equals("1")) {
            JOptionPane.showMessageDialog(rootPane, "EL numero de cuenta esta bien");
            this.jTextNombreDeespotiante.setEnabled(true);
            this.jTextApellidoDepositante.setEnabled(true);
            this.jTextCedulaDespositante.setEnabled(true);
            this.jTextDinero.setEnabled(true);
            this.jButtonDespositar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(rootPane, "el numero de cuenta esta mal");
            this.jTextNombreDeespotiante.setEnabled(false);
            this.jTextApellidoDepositante.setEnabled(false);
            this.jTextCedulaDespositante.setEnabled(false);
            this.jTextDinero.setEnabled(false);
        }


    }//GEN-LAST:event_jButonBuscarActionPerformed

    private void jButtonDespositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespositarActionPerformed
        // TODO add your handling code here:
       
        
        int saldoDeposito = 0;
        //ArrayPersonaCuentas = objImpPersonaCuenta.ImportarPersonaCuentas();
        System.out.println(ArrayPersonaCuentas);
        String aNCuenta = this.jTextNCuenta.getText();

        objDepositante = objManDepositante.CrearDepositante(this.jTextNombreDeespotiante.getText(),
                this.jTextApellidoDepositante.getText(), this.jTextCedulaDespositante.getText(),
                this.jTextDinero.getText(),
                objManPersonaCuenta.BuscarPERsonaCuenta(ArrayPersonaCuentas, aNCuenta));

        saldoDeposito = Integer.parseInt(this.jTextDinero.getText());
        objManPersonaCuenta.ActualizarSaldo(ArrayPersonaCuentas, saldoDeposito, aNCuenta);
        System.out.println("DDDDDDDDDDDDDD" + objDepositante.getPersonaCuenta().getnCuenta());

        ArrayDepositante.add(objDepositante);
        //ArrayPersonaCuentas.add(objPersonaCuenta);
        try {
            objImpDepositante.GuardaArchivoDepositante(ArrayDepositante);
            objImpPersonaCuenta.GuardaArchivoPersonaCuenta(ArrayPersonaCuentas);
            System.out.println(ArrayDepositante);
        } catch (IOException ex) {
            Logger.getLogger(Deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();


    }//GEN-LAST:event_jButtonDespositarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextDineroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDineroKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros.");
            
        }
        
    }//GEN-LAST:event_jTextDineroKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButonBuscar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDespositar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextApellidoDepositante;
    private javax.swing.JTextField jTextCedulaDespositante;
    private javax.swing.JTextField jTextDinero;
    private javax.swing.JTextField jTextNCuenta;
    private javax.swing.JTextField jTextNombreDeespotiante;
    // End of variables declaration//GEN-END:variables
}
