/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Depositante;
import Clases.PersonaCuenta;
import Logica.ImpDepositante;
import Logica.ImpPersonaCuenta;
import Logica.ManDepositante;
import Logica.ManPersonaCuenta;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author STALIN
 */
public class Retiro extends javax.swing.JFrame {

    /**
     * Creates new form Retiro
     */
    ImpPersonaCuenta objImpPersonaCuenta = new ImpPersonaCuenta();
    ImpDepositante objImpCliente = new ImpDepositante();

    ManPersonaCuenta objManPersonaCuenta = new ManPersonaCuenta();
    ManDepositante objManCliente = new ManDepositante();

    PersonaCuenta objPersonaCuenta = new PersonaCuenta();
    Depositante objCliente = new Depositante();

    ArrayList<PersonaCuenta> ArrayPersonaCuentas = new ArrayList<PersonaCuenta>();
    ArrayList<Depositante> ArrayClientes = new ArrayList<Depositante>();

    public Retiro() {
        initComponents();
        ArrayPersonaCuentas = objImpPersonaCuenta.ImportarPersonaCuentas();
        ArrayClientes = objImpCliente.ImportarDepositante();
        this.jTextApellidoCuenta.setEnabled(false);
        this.jTextNCuenta.setEnabled(false);
        this.jTextNombreCuenta.setEnabled(false);
        this.jTextSaldoCuenta.setEnabled(false);
        this.jTextTipoCuenta.setEnabled(false);
        this.jTextRetirar.setEnabled(false);
        this.jTCedula.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextNombreCuenta = new javax.swing.JTextField();
        jTextApellidoCuenta = new javax.swing.JTextField();
        jTextNCuenta = new javax.swing.JTextField();
        jTextSaldoCuenta = new javax.swing.JTextField();
        jTextTipoCuenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextRetirar = new javax.swing.JTextField();
        jTCedula = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Numero Cuenta:");

        jLabel5.setText("saldo:");

        jLabel6.setText("Cuenta:");

        jTextNCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNCuentaActionPerformed(evt);
            }
        });

        jTextTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTipoCuentaActionPerformed(evt);
            }
        });

        jLabel7.setText("Retirar:");

        jTextRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextRetirarKeyTyped(evt);
            }
        });

        jTCedula.setText("retirar");
        jTCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCedulaActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("RETIRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jTextRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTCedula))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextApellidoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNCuenta)
                            .addComponent(jTextSaldoCuenta)
                            .addComponent(jTextTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscar)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextApellidoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCedula))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextNCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNCuentaActionPerformed

    private void jTextTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTipoCuentaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:.
        String nC = objManPersonaCuenta.BuscarPersonaCuentaCedula(ArrayPersonaCuentas, this.jTextCedula.getText());

        objPersonaCuenta = objManPersonaCuenta.BuscarPersonaCedula2(ArrayPersonaCuentas, this.jTextCedula.getText());
        if (nC.equals("1")) {
            this.jTextRetirar.setEnabled(true);
            this.jTCedula.setEnabled(true);
            String cuenta = "";

            this.jTextNombreCuenta.setText(String.valueOf(objPersonaCuenta.getNombre()));
            this.jTextApellidoCuenta.setText(String.valueOf(objPersonaCuenta.getApellido()));

            this.jTextSaldoCuenta.setText(String.valueOf(objPersonaCuenta.getSaldo()));
            this.jTextNCuenta.setText(String.valueOf(objPersonaCuenta.getnCuenta()));

            if (objPersonaCuenta.getActivo().equals("1")) {
                cuenta = "corriente";
            }
            if (objPersonaCuenta.getActivo().equals("0")) {
                cuenta = "ahorros";
            }

            this.jTextTipoCuenta.setText(cuenta);

        }
        if (nC != "1") {
            JOptionPane.showMessageDialog(rootPane, "EL numero de cuenta NO es correcto");
            this.jTextApellidoCuenta.setText(null);
            this.jTextCedula.setText(null);
            this.jTextNCuenta.setText(null);
            this.jTextNombreCuenta.setText(null);
            this.jTextSaldoCuenta.setText(null);
            this.jTextTipoCuenta.setText(null);
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCedulaActionPerformed
        // TODO add your handling code here:
        int saldoRetiro = 0;
      //  ArrayPersonaCuentas = objImpPersonaCuenta.ImportarPersonaCuentas();

        String aNCuenta = this.jTextNCuenta.getText().trim();

        saldoRetiro = Integer.parseInt(this.jTextRetirar.getText());

        objManPersonaCuenta.ActualizarSaldoRetiro2(ArrayPersonaCuentas, saldoRetiro, aNCuenta);

        //ArrayPersonaCuentas.add(objManPersonaCuenta);
        //ArrayPersonaCuentas.add(objPersonaCuenta);
        try {

            objImpPersonaCuenta.GuardaArchivoPersonaCuenta(ArrayPersonaCuentas);
        } catch (IOException ex) {
            Logger.getLogger(Deposito.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jTextApellidoCuenta.setText(null);
        this.jTextCedula.setText(null);
        this.jTextNCuenta.setText(null);
        this.jTextNombreCuenta.setText(null);
        this.jTextSaldoCuenta.setText(null);
        this.jTextTipoCuenta.setText(null);

    }//GEN-LAST:event_jTCedulaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextRetirarKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros.");
            
        }
    }//GEN-LAST:event_jTextRetirarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jTCedula;
    private javax.swing.JTextField jTextApellidoCuenta;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextNCuenta;
    private javax.swing.JTextField jTextNombreCuenta;
    private javax.swing.JTextField jTextRetirar;
    private javax.swing.JTextField jTextSaldoCuenta;
    private javax.swing.JTextField jTextTipoCuenta;
    // End of variables declaration//GEN-END:variables
}
